//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.ComentarioEquipo = new HashSet<ComentarioEquipo>();
            this.EquipoUsuario = new HashSet<EquipoUsuario>();
            this.ImagenEquipo = new HashSet<ImagenEquipo>();
            this.SkillEquipo = new HashSet<SkillEquipo>();
        }
    
        public int EquipoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte DeporteId { get; set; }
        public int UsuarioCapitanId { get; set; }
        public string Estado { get; set; }
        public Nullable<byte> DistritoId { get; set; }
        public Nullable<byte> CategoriaId { get; set; }
        public string ImagenPortadaUrl { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioEquipo> ComentarioEquipo { get; set; }
        public virtual Deporte Deporte { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoUsuario> EquipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenEquipo> ImagenEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillEquipo> SkillEquipo { get; set; }
    }
}
