//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspacioDeportivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EspacioDeportivo()
        {
            this.HorarioEspacioDeportivo = new HashSet<HorarioEspacioDeportivo>();
        }
    
        public int EspacioDeportivoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> EstablecimientoId { get; set; }
        public Nullable<byte> DeporteId { get; set; }
        public Nullable<byte> TipoSuperficieId { get; set; }
        public string Estado { get; set; }
    
        public virtual Deporte Deporte { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual TipoSuperficie TipoSuperficie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioEspacioDeportivo> HorarioEspacioDeportivo { get; set; }
    }
}
