//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstablecimientoServicio
    {
        public int EstablecimientoId { get; set; }
        public short ServicioId { get; set; }
        public string Estado { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
