//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Establecimiento()
        {
            this.EspacioDeportivo = new HashSet<EspacioDeportivo>();
            this.EstablecimientoServicio = new HashSet<EstablecimientoServicio>();
        }
    
        public int EstablecimientoId { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<byte> DistritoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UsuarioPropietarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspacioDeportivo> EspacioDeportivo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstablecimientoServicio> EstablecimientoServicio { get; set; }
    }
}
