//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioEspacioDeportivo
    {
        public int HorarioId { get; set; }
        public int EspacioDeportivoId { get; set; }
        public string Estado { get; set; }
        public Nullable<int> ReservaId { get; set; }
    
        public virtual EspacioDeportivo EspacioDeportivo { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
