//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenEquipo
    {
        public int ImagenEquipoId { get; set; }
        public int EquipoId { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
        public string ImagenUrl { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
