//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reto
    {
        public int RetoId { get; set; }
        public int EquipoRetadorId { get; set; }
        public int EquipoRetadoId { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public int ReservaId { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
