//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillEquipo
    {
        public int EquipoId { get; set; }
        public byte SkillId { get; set; }
        public decimal Promedio { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
